use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub enum Lang {
    Fr,
    En,
}

impl Default for Lang {
    fn default() -> Self {
        Lang::Fr
    }
}

impl Lang {
    pub fn t<'a>(&self, key: &'a str) -> &'a str {
        match (self, key) {
            // Tabs
            (Lang::Fr, "tab_principal") => "📋 Principal",
            (Lang::En, "tab_principal") => "📋 Main",
            (Lang::Fr, "tab_logs") => "📜 Logs",
            (Lang::En, "tab_logs") => "📜 Logs",
            (Lang::Fr, "tab_huggingface") => "🤗 HuggingFace",
            (Lang::En, "tab_huggingface") => "🤗 HuggingFace",
            (Lang::Fr, "tab_settings") => "⚙️ Paramètres",
            (Lang::En, "tab_settings") => "⚙️ Settings",
            (Lang::Fr, "tab_aide") => "📖 Llama Aide",
            (Lang::En, "tab_aide") => "📖 Llama Help",

            // Sections
            (Lang::Fr, "section_models") => "📁 Modèles",
            (Lang::En, "section_models") => "📁 Models",
            (Lang::Fr, "section_versions") => "🦙 Versions",
            (Lang::En, "section_versions") => "🦙 Versions",
            (Lang::Fr, "section_update") => "🔄 Mise à jour",
            (Lang::En, "section_update") => "🔄 Update",
            (Lang::Fr, "section_restore") => "♻️ Restauration",
            (Lang::En, "section_restore") => "♻️ Restore",
            (Lang::Fr, "section_logs") => "📝 Logs",
            (Lang::En, "section_logs") => "📝 Logs",
            (Lang::Fr, "section_conversation") => "💬 Conversation",
            (Lang::En, "section_conversation") => "💬 Conversation",
            (Lang::Fr, "section_configs") => "📋 Configs",
            (Lang::En, "section_configs") => "📋 Configs",
            (Lang::Fr, "section_config") => "⚙️ Configuration",
            (Lang::En, "section_config") => "⚙️ Configuration",
            (Lang::Fr, "section_system") => "💻 Système",
            (Lang::En, "section_system") => "💻 System",
            (Lang::Fr, "section_ram") => "💾 RAM",
            (Lang::En, "section_ram") => "💾 RAM",
            (Lang::Fr, "section_disks") => "💾 Disques",
            (Lang::En, "section_disks") => "💾 Disks",
            (Lang::Fr, "section_paths") => "🔧 Chemins",
            (Lang::En, "section_paths") => "🔧 Paths",
            (Lang::Fr, "section_lang") => "🌐 Langue",
            (Lang::En, "section_lang") => "🌐 Language",

            // Buttons
            (Lang::Fr, "btn_scan") => "🔍 Scanner",
            (Lang::En, "btn_scan") => "🔍 Scan",
            (Lang::Fr, "btn_check_versions") => "🔄 Vérifier versions",
            (Lang::En, "btn_check_versions") => "🔄 Check versions",
            (Lang::Fr, "btn_launch_update") => "🚀 Lancer la mise à jour",
            (Lang::En, "btn_launch_update") => "🚀 Launch update",
            (Lang::Fr, "btn_scan_backups") => "🔍 Scanner les sauvegardes",
            (Lang::En, "btn_scan_backups") => "🔍 Scan backups",
            (Lang::Fr, "btn_restore") => "♻️ Restaurer",
            (Lang::En, "btn_restore") => "♻️ Restore",
            (Lang::Fr, "btn_delete") => "🗑️",
            (Lang::En, "btn_delete") => "🗑️",
            (Lang::Fr, "btn_save") => "💾 Sauvegarder",
            (Lang::En, "btn_save") => "💾 Save",
            (Lang::Fr, "btn_apply") => "💾 Appliquer",
            (Lang::En, "btn_apply") => "💾 Apply",
            (Lang::Fr, "btn_new_config") => "➕ Créer",
            (Lang::En, "btn_new_config") => "➕ Create",
            (Lang::Fr, "btn_stop") => "⏹️ Arrêter",
            (Lang::En, "btn_stop") => "⏹️ Stop",
            (Lang::Fr, "btn_start") => "▶️ Lancer",
            (Lang::En, "btn_start") => "▶️ Start",
            (Lang::Fr, "btn_retry") => "Réessayer",
            (Lang::En, "btn_retry") => "Retry",
            (Lang::Fr, "btn_search") => "🔍 Chercher",
            (Lang::En, "btn_search") => "🔍 Search",
            (Lang::Fr, "btn_download") => "⬇️",
            (Lang::En, "btn_download") => "⬇️",
            (Lang::Fr, "btn_cancel") => "❌ Annuler",
            (Lang::En, "btn_cancel") => "❌ Cancel",
            (Lang::Fr, "btn_clear") => "🗑️ Effacer",
            (Lang::En, "btn_clear") => "🗑️ Clear",
            (Lang::Fr, "btn_file") => "📂 Fichier",
            (Lang::En, "btn_file") => "📂 File",
            (Lang::Fr, "btn_refresh") => "🔄",
            (Lang::En, "btn_refresh") => "🔄",
            (Lang::Fr, "btn_folder") => "📂",
            (Lang::En, "btn_folder") => "📂",
            (Lang::Fr, "btn_save_paths") => "💾 Sauvegarder les chemins",
            (Lang::En, "btn_save_paths") => "💾 Save paths",
            (Lang::Fr, "btn_all") => "Tout",
            (Lang::En, "btn_all") => "All",
            (Lang::Fr, "btn_ok") => "OK",
            (Lang::En, "btn_ok") => "OK",
            (Lang::Fr, "btn_send") => "➤",
            (Lang::En, "btn_send") => "➤",

            // Labels
            (Lang::Fr, "lbl_search") => "🔍",
            (Lang::En, "lbl_search") => "🔍",
            (Lang::Fr, "lbl_cli") => "💬 CLI:",
            (Lang::En, "lbl_cli") => "💬 CLI:",
            (Lang::Fr, "lbl_srv") => "🌐 SRV:",
            (Lang::En, "lbl_srv") => "🌐 SRV:",
            (Lang::Fr, "lbl_prompt") => "Prompt:",
            (Lang::En, "lbl_prompt") => "Prompt:",
            (Lang::Fr, "lbl_vram") => "VRAM",
            (Lang::En, "lbl_vram") => "VRAM",
            (Lang::Fr, "lbl_model") => "Modèle:",
            (Lang::En, "lbl_model") => "Model:",
            (Lang::Fr, "lbl_mode") => "Mode:",
            (Lang::En, "lbl_mode") => "Mode:",
            (Lang::Fr, "lbl_backend") => "Backend:",
            (Lang::En, "lbl_backend") => "Backend:",
            (Lang::Fr, "lbl_new") => "Nouvelle:",
            (Lang::En, "lbl_new") => "New:",
            (Lang::Fr, "lbl_advanced") => "🔧 Avancé",
            (Lang::En, "lbl_advanced") => "🔧 Advanced",
            (Lang::Fr, "lbl_extra_args") => "Args supplémentaires:",
            (Lang::En, "lbl_extra_args") => "Extra args:",
            (Lang::Fr, "lbl_cuda_local") => "📦 CUDA Locale :",
            (Lang::En, "lbl_cuda_local") => "📦 CUDA Local :",
            (Lang::Fr, "lbl_vulkan_local") => "📦 Vulkan Locale :",
            (Lang::En, "lbl_vulkan_local") => "📦 Vulkan Local :",
            (Lang::Fr, "lbl_cuda_github") => "🌐 CUDA Github :",
            (Lang::En, "lbl_cuda_github") => "🌐 CUDA GitHub :",
            (Lang::Fr, "lbl_vulkan_github") => "🌐 Vulkan Github :",
            (Lang::En, "lbl_vulkan_github") => "🌐 Vulkan GitHub :",
            (Lang::Fr, "lbl_free") => "Libre:",
            (Lang::En, "lbl_free") => "Free:",
            (Lang::Fr, "lbl_ram") => "RAM",
            (Lang::En, "lbl_ram") => "RAM",
            (Lang::Fr, "lbl_gpu") => "GPU",
            (Lang::En, "lbl_gpu") => "GPU",
            (Lang::Fr, "lbl_filters") => "Filtres:",
            (Lang::En, "lbl_filters") => "Filters:",

            // Status / Messages
            (Lang::Fr, "msg_no_models") => "Aucun modèle",
            (Lang::En, "msg_no_models") => "No models",
            (Lang::Fr, "msg_scanning") => "🔄 Recherche...",
            (Lang::En, "msg_scanning") => "🔄 Searching...",
            (Lang::Fr, "msg_no_backups") => "Aucune sauvegarde trouvée",
            (Lang::En, "msg_no_backups") => "No backups found",
            (Lang::Fr, "msg_checking") => "🔄 Vérification...",
            (Lang::En, "msg_checking") => "🔄 Checking...",
            (Lang::Fr, "msg_no_config") => "Sélectionnez une config",
            (Lang::En, "msg_no_config") => "Select a config",
            (Lang::Fr, "msg_hf_empty") => "Entrez une recherche pour trouver des modèles GGUF",
            (Lang::En, "msg_hf_empty") => "Enter a search to find GGUF models",
            (Lang::Fr, "msg_conv_empty") => "Lancez un modèle en mode CLI ou Serveur pour voir la sortie ici.",
            (Lang::En, "msg_conv_empty") => "Launch a model in CLI or Server mode to see output here.",
            (Lang::Fr, "msg_waiting") => "⏳ En attente de réponse...",
            (Lang::En, "msg_waiting") => "⏳ Waiting for response...",
            (Lang::Fr, "msg_search_progress") => "🔍 Recherche en cours...",
            (Lang::En, "msg_search_progress") => "🔍 Searching...",
            (Lang::Fr, "msg_no_models_found") => "⚠️ Aucun modèle trouvé",
            (Lang::En, "msg_no_models_found") => "⚠️ No models found",
            (Lang::Fr, "msg_models_scanned") => "✅ Modèles scannés",
            (Lang::En, "msg_models_scanned") => "✅ Models scanned",
            (Lang::Fr, "msg_saved") => "✅ Sauvegardé",
            (Lang::En, "msg_saved") => "✅ Saved",
            (Lang::Fr, "msg_ready") => "Prêt",
            (Lang::En, "msg_ready") => "Ready",
            (Lang::Fr, "msg_vram_insufficient") => "❌ VRAM insuffisante",
            (Lang::En, "msg_vram_insufficient") => "❌ Insufficient VRAM",

            // Log levels (same in both languages)
            (_, "log_trace") => "Trace",
            (_, "log_debug") => "Debug",
            (_, "log_info") => "Info",
            (_, "log_warn") => "Warn",
            (_, "log_error") => "Error",

            // HuggingFace filters
            (_, "hf_all") => "Tout",
            (_, "hf_finetunes") => "Finetunes",
            (_, "hf_adapters") => "Adapters",
            (_, "hf_merges") => "Merges",

            // Server/CLI mode
            (Lang::Fr, "mode_server") => "Serveur",
            (Lang::En, "mode_server") => "Server",
            (_, "mode_cli") => "CLI",

            // CUDA / Vulkan labels in settings
            (_, "lbl_cuda") => "CUDA :",
            (_, "lbl_vulkan") => "Vulkan :",
            (Lang::Fr, "lbl_dir_cuda") => "Dossier CUDA :",
            (Lang::En, "lbl_dir_cuda") => "CUDA folder:",
            (Lang::Fr, "lbl_dir_vulkan") => "Dossier Vulkan :",
            (Lang::En, "lbl_dir_vulkan") => "Vulkan folder:",
            (Lang::Fr, "lbl_dir_models") => "Dossier Modèles :",
            (Lang::En, "lbl_dir_models") => "Models folder:",
            (Lang::Fr, "lbl_dir_temp") => "Dossier Temp :",
            (Lang::En, "lbl_dir_temp") => "Temp folder:",
            (Lang::Fr, "lbl_dir_backups") => "Dossier Sauvegardes :",
            (Lang::En, "lbl_dir_backups") => "Backups folder:",

            // Conversation labels
            (Lang::Fr, "conv_user") => "Utilisateur :",
            (Lang::En, "conv_user") => "User :",
            (Lang::Fr, "conv_model") => "Modèle :",
            (Lang::En, "conv_model") => "Model :",
            (Lang::Fr, "conv_server") => "Serveur :",
            (Lang::En, "conv_server") => "Server :",
            (Lang::Fr, "conv_waiting") => "⏳ En attente de réponse...",
            (Lang::En, "conv_waiting") => "⏳ Waiting for response...",

            (Lang::Fr, "lbl_models_count") => "modèles:",
            (Lang::En, "lbl_models_count") => "models:",
            (Lang::Fr, "lbl_backups_found") => "sauvegardes trouvées",
            (Lang::En, "lbl_backups_found") => "backups found",
            (Lang::Fr, "lbl_selected") => "Sélectionné",
            (Lang::En, "lbl_selected") => "Selected",
            (Lang::Fr, "lbl_hint_prompt") => "Tapez votre message...",
            (Lang::En, "lbl_hint_prompt") => "Type your message...",
            (Lang::Fr, "msg_select_model") => "Sélectionner...",
            (Lang::En, "msg_select_model") => "Select...",
            (Lang::Fr, "lbl_none") => "Aucun",
            (Lang::En, "lbl_none") => "None",
            (Lang::Fr, "tab_logs_all") => "📜 Tous",
            (Lang::En, "tab_logs_all") => "📜 All",
            (Lang::Fr, "tab_logs_srv") => "🌐 Serveur",
            (Lang::En, "tab_logs_srv") => "🌐 Server",
            (Lang::Fr, "tab_logs_file") => "📂 Fichier journal",
            (Lang::En, "tab_logs_file") => "📂 Log file",
            (Lang::Fr, "tab_logs_buffer") => "💾 Buffer mémoire",
            (Lang::En, "tab_logs_buffer") => "💾 Memory buffer",
            (Lang::Fr, "lbl_hint_hf") => "Rechercher un modèle GGUF...",
            (Lang::En, "lbl_hint_hf") => "Search GGUF model...",
            (Lang::Fr, "lbl_hf_results") => "résultat(s)",
            (Lang::En, "lbl_hf_results") => "result(s)",
            (Lang::Fr, "lbl_free_vram") => "VRAM libre",
            (Lang::En, "lbl_free_vram") => "Free VRAM",
            (Lang::Fr, "lbl_lang") => "Langue:",
            (Lang::En, "lbl_lang") => "Language:",

            // Aide tab
            (Lang::Fr, "btn_load_cli_help") => "📖 Charger l'aide CLI",
            (Lang::En, "btn_load_cli_help") => "📖 Load CLI help",
            (Lang::Fr, "btn_load_srv_help") => "📖 Charger l'aide Serveur",
            (Lang::En, "btn_load_srv_help") => "📖 Load Server help",
            (Lang::Fr, "msg_help_loading") => "⏳ Chargement...",
            (Lang::En, "msg_help_loading") => "⏳ Loading...",
            (Lang::Fr, "msg_help_prompt") => "Cliquez sur le bouton pour charger l'aide de l'exécutable.",
            (Lang::En, "msg_help_prompt") => "Click the button to load the executable help.",
            (Lang::Fr, "msg_no_cli_exe") => "Aucun exécutable CLI trouvé. Configurez le chemin dans Paramètres.",
            (Lang::En, "msg_no_cli_exe") => "No CLI executable found. Set the path in Settings.",
            (Lang::Fr, "msg_no_srv_exe") => "Aucun exécutable Serveur trouvé. Configurez le chemin dans Paramètres.",
            (Lang::En, "msg_no_srv_exe") => "No Server executable found. Set the path in Settings.",

            // Warning
            (Lang::Fr, "warning_title") => "⚠️ Avertissement",
            (Lang::En, "warning_title") => "⚠️ Warning",

            // Default fallback
            _ => key,
        }
    }
}
